### ISSUE TITLE
Remove access policy from user key `refresh`

### ISSUE THREAD

**Issue by tbrezot** [Cosmian/cover_crypt#77]
For now, the user key refresh is based on a user [`access_policy`](https://github.com/Cosmian/cover_crypt/blob/f3d1b7c40f685d21b473c51cc0ae9845050b8cb2/src/api.rs#L112). It means this access policy has to be regenerated at each refresh.

It would be possible to update a user key without this access policy. Indeed, the master secret key keeps track of every generated sub-keys. For each right, the refresh operation would deliver the new subkey to a user if his key already contains an valid subkey for this right.

**Comment by tbrezot** [comment]
To prevent forgery of the user key, a hash should be added to each user key. This hash would be computed using:
- the entire user secret key;
- the master secret key scalar `s`.
Only a master authority should be able to compute this hash.

**Comment by ackRow** [comment]
See https://github.com/Cosmian/cover_crypt/pull/120
